language: c
sudo: required
install:
  - wget http://www.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo_latest_all.deb
  - sudo dpkg -i globus-toolkit-repo_latest_all.deb
  - sudo apt-get update -qq
  - sudo apt-get install -qq globus-data-management-sdk libglobus-usage-dev
  - pkg-config --exists --print-errors "globus-gss-assist >= 2, globus-gssapi-gsi, globus-usage >= 1, globus-common, openssl"
  - pkg-config --libs "globus-gss-assist >= 2, globus-gssapi-gsi, globus-usage >= 1, globus-common, openssl"
script:
  - autoreconf
  - ./configure --with-globus
  - make
after_success:
  - ./ssh -V
